import { Component } from '@angular/core';
import { StudyCardGrid } from '../../shared/components/study-card-grid/study-card-grid';
import { StudyCardItem } from '../../shared/interfaces/study-template.interface';

@Component({
  selector: 'app-frontend',
  standalone: true,
  imports: [StudyCardGrid],
  templateUrl: './frontend.component.html',
  styleUrl: './frontend.component.scss',
})
export class FrontendComponent {
  readonly items: StudyCardItem[] = [
    {
      id: 1,
      title: 'Angular',
      description: 'Componentes, rotas, services, signals e arquitetura moderna.',
      imageUrl: 'assets/images/studies/angular.png',
      iconClass: 'pi-desktop',
      skill: 'Frontend',
      detailRoute: '/frontend/angular',
    },
    {
      id: 2,
      title: 'TypeScript',
      description: 'Tipos, interfaces, generics e boas práticas para aplicações escaláveis.',
      imageUrl: 'assets/images/studies/typescript.png',
      iconClass: 'pi-code',
      skill: 'Linguagem',
      detailRoute: '/frontend/typescript',
    },
    {
      id: 3,
      title: 'SCSS',
      description: 'Organização de estilos, variáveis, mixins, responsividade e design system.',
      imageUrl: 'assets/images/studies/scss.png',
      iconClass: 'pi-palette',
      skill: 'Estilo',
      detailRoute: '/frontend/scss',
    },
    {
      id: 4,
      title: 'Jest',
      description: 'Testes unitários para componentes, services e fluxos assíncronos.',
      imageUrl: 'assets/images/studies/jest.png',
      iconClass: 'pi-check-circle',
      skill: 'Testes',
      detailRoute: '/frontend/jest',
    },
    {
      id: 5,
      title: 'PrimeNG',
      description: 'Componentes visuais modernos para acelerar interfaces Angular.',
      imageUrl: 'assets/images/studies/primeng.png',
      iconClass: 'pi-prime',
      skill: 'UI',
      detailRoute: '/frontend/primeng',
    },
    {
      id: 6,
      title: 'RxJS',
      description: 'Streams, Observables, operadores e controle de eventos assíncronos.',
      imageUrl: 'assets/images/studies/rxjs.png',
      iconClass: 'pi-sync',
      skill: 'Angular',
      detailRoute: '/frontend/rxjs',
    },
    {
      id: 7,
      title: 'Acessibilidade',
      description: 'Semântica, navegação por teclado, contraste e boas práticas inclusivas.',
      imageUrl: 'assets/images/studies/accessibility.png',
      iconClass: 'pi-eye',
      skill: 'UX',
      detailRoute: '/frontend/acessibilidade',
    },
    {
      id: 8,
      title: 'Responsividade',
      description: 'Mobile first, grid, flexbox, media queries e layouts adaptáveis.',
      imageUrl: 'assets/images/studies/responsive.png',
      iconClass: 'pi-mobile',
      skill: 'Layout',
      detailRoute: '/frontend/responsividade',
    },
    {
      id: 9,
      title: 'Design System',
      description: 'Tokens, padrões visuais, componentes reutilizáveis e consistência.',
      imageUrl: 'assets/images/studies/design-system.png',
      iconClass: 'pi-sitemap',
      skill: 'UI',
      detailRoute: '/frontend/design-system',
    },
    {
      id: 10,
      title: 'HTML Semântico',
      description: 'Estrutura correta de páginas, landmarks e acessibilidade nativa.',
      imageUrl: 'assets/images/studies/html.png',
      iconClass: 'pi-align-left',
      skill: 'Base Web',
      detailRoute: '/frontend/html-semantico',
    },
    {
      id: 11,
      title: 'Performance Web',
      description: 'Boas práticas para otimizar carregamento, bundle e experiência.',
      imageUrl: 'assets/images/studies/performance-web.png',
      iconClass: 'pi-bolt',
      skill: 'Performance',
      detailRoute: '/frontend/performance-web',
    },
    {
      id: 12,
      title: 'Arquitetura Frontend',
      description: 'Organização de pastas, responsabilidades e padrões de crescimento.',
      imageUrl: 'assets/images/studies/frontend-architecture.png',
      iconClass: 'pi-building',
      skill: 'Arquitetura',
      detailRoute: '/frontend/arquitetura',
    },
  ];
}
